//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Start
    {
        public string CourseNo { get; set; }
        public string Title { get; set; }
        public Nullable<int> CrediteNo { get; set; }
        public string Syllabus { get; set; }
        public string FKDCode { get; set; }
        public string InstructorNo { get; set; }
        public string InstructorName { get; set; }
        public int SectionNo { get; set; }
        public string Semester { get; set; }
        public string Year { get; set; }
        public long TaskNo { get; set; }
        public string TaskPath { get; set; }
        public string FKTypeCode { get; set; }
    }
}
